spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/seller
    username: test
    password: 12345678
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml

springdoc:
  swagger-ui:
    path: swagger-ui.html

logging.level:
  ROOT: INFO
  org.springframework: DEBUG